# Generated by Django 4.2.1 on 2023-06-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30)),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(default='', max_length=100)),
                ('autor', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('cuerpo', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='imagenes noticias')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('tipo_usuario', models.BooleanField()),
            ],
        ),
    ]
