# Generated by Django 4.2.1 on 2023-06-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='subtitulo',
            field=models.CharField(max_length=100),
        ),
    ]
