# Generated by Django 4.2.1 on 2023-06-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0005_contacto_alter_noticia_autor_alter_usuarios_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='tipo_contacto',
            field=models.IntegerField(choices=[[0, 'Sugerencia'], [1, 'Reclamo']], null=True),
        ),
    ]
