# Generated by Django 4.2.1 on 2023-06-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0006_contacto_tipo_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.IntegerField(choices=[[0, 'Chile'], [1, 'Internacional'], [2, 'Deportes']], null=True),
        ),
    ]
