# Generated by Django 4.2.1 on 2023-06-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0007_alter_noticia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.CharField(max_length=50),
        ),
    ]
