# Generated by Django 4.2.1 on 2023-06-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0010_revisar_noticia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Revisar_Noticia',
            new_name='Revisar',
        ),
    ]
