# Generated by Django 4.2.1 on 2023-06-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0011_rename_revisar_noticia_revisar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tipo_contacto',
            field=models.IntegerField(choices=[[0, 'Sugerencia'], [1, 'Reclamo'], [2, 'Felicitaciones']], null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.IntegerField(choices=[[0, 'Chile'], [1, 'Internacional'], [2, 'Deportes'], [3, 'Otros']], null=True),
        ),
        migrations.AlterField(
            model_name='revisar',
            name='autor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='revisar',
            name='categoria',
            field=models.IntegerField(choices=[[0, 'Chile'], [1, 'Internacional'], [2, 'Deportes'], [3, 'Otros']], null=True),
        ),
    ]
