# Generated by Django 4.2.1 on 2023-06-26 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0013_autor_delete_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisar',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.autor'),
        ),
    ]
