# Generated by Django 4.2.1 on 2023-06-26 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0015_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisar',
            name='categoria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appweb.categorias'),
        ),
    ]
