# Generated by Django 4.2.1 on 2023-06-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0023_alter_autor_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
