# Generated by Django 4.2.1 on 2023-06-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0024_alter_autor_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes perfil'),
        ),
    ]
