# Generated by Django 4.2.1 on 2023-07-01 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appweb', '0025_autor_descripcion_autor_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticia',
            name='estado',
            field=models.IntegerField(choices=[[0, 'Creada'], [1, 'Aprobada'], [2, 'Rechazada']], default=0),
        ),
        migrations.AddField(
            model_name='noticia',
            name='motivo',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Revisar',
        ),
    ]
