# Generated by Django 4.2.1 on 2023-07-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0026_autor_usuario_noticia_estado_noticia_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes_perfil'),
        ),
    ]
