# Generated by Django 4.2.1 on 2023-07-01 16:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0027_alter_autor_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
