# Generated by Django 4.2.1 on 2023-07-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0028_alter_noticia_cuerpo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes_postulantes')),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
    ]
