# Generated by Django 4.2.1 on 2023-07-06 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0030_postulacion_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacion',
            name='fecha_postulacion',
        ),
    ]
