# Generated by Django 4.2.1 on 2023-07-13 04:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0036_alter_autor_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
