# Generated by Django 4.2.1 on 2023-07-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0037_alter_postulacion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
