# Generated by Django 4.2.1 on 2023-07-14 01:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0039_alter_noticia_imagen_alter_postulacion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
